[build]
  # Build command for the web app
  command = "npm --workspace @vigor/web run build"
  
  # Publish directory (Next.js output)
  publish = "apps/web/.next"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Build optimizations
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js Image Optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

# Handle _ipx image optimization (alternative)
[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

# Redirect rules for SPA routing (catch-all for Next.js client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production.environment]
  NEXT_PUBLIC_APP_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_APP_ENV = "preview"

[context.branch-deploy.environment]
  NEXT_PUBLIC_APP_ENV = "development"
