[build]
  # Build command for monorepo - create symlink for node_modules and build
  command = "npm install && cd apps/web && ln -sf ../../node_modules . && npm run build"

  # Publish directory (Next.js output with Netlify plugin)
  publish = "apps/web/.next"

  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Build optimizations
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    # Tell the plugin where to find the Next.js app in monorepo
    distDir = "apps/web/.next"

# Static assets served directly (no image optimization)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for SPA routing (exclude static assets)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production.environment]
  NEXT_PUBLIC_APP_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_APP_ENV = "preview"

[context.branch-deploy.environment]
  NEXT_PUBLIC_APP_ENV = "development"
